services:
  sandbox-staging:
    build:
      context: ..
      dockerfile: sandbox/Dockerfile
    ports: ["8001:8000"]
    # Resource limits (compose may not enforce strictly; adjust as needed)
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G
    ulimits:
      nproc: 65535
      nofile: 131072
      as: -1
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/healthz | grep -q ok"]
      interval: 5s
      timeout: 3s
      retries: 10
