services:
  backend:
    build:
      context: .
      dockerfile: sandbox/Dockerfile
    container_name: symbiont-backend
    command: ["uvicorn", "sandbox.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.50"
          memory: 512M
    healthcheck:
      test:
        - "CMD-SHELL"
        - "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz').read()\""
      interval: 10s
      timeout: 3s
      retries: 5

  ui:
    build:
      context: .
      dockerfile: sandbox/Dockerfile
    container_name: symbiont-ui
    command:
      [
        "streamlit",
        "run",
        "app.py",
        "--server.headless",
        "true",
        "--server.port",
        "8501",
        "--server.address",
        "0.0.0.0",
      ]
    ports:
      - "8502:8501"
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1.5G
        reservations:
          cpus: "0.5"
          memory: 512M
