db_path: "./data/symbiont.db"
env: "dev"
max_tokens: 6000
cycle_budget_seconds: 60
consensus: {min_agree: 2, require_critic_ok: true}
initiative: {enabled: false, watchers: []}
tools: {allow_code_runner: true, allow_files: true, network_access: false}
llm: {provider: "none", model: "phi3:mini", cmd: "", timeout_seconds: 25}
