db_path: "./data/symbiont.db"
env: "dev"
max_tokens: 6000
cycle_budget_seconds: 60
consensus: {min_agree: 2, require_critic_ok: true}
initiative:
  enabled: false
  repo_path: "."
  watchers: ["file", "git", "timer"]
  idle_minutes: 120
  timer_minutes: 120
  trigger_mode: "idle_and_timer"  # one of: any, idle_and_timer
  goal_template: "Repo idle; propose one 10-minute refactor and draft a script."
tools: {allow_code_runner: true, allow_files: true, network_access: false}
llm: {provider: "none", model: "phi3:mini", cmd: "", timeout_seconds: 25}
voice: {enabled: false, stt: "none", tts: "say", wake_word: "symbiont"}
guard: {auto_approve_safe: false}
browser: {enabled: false, allowlist: ["https://docs.astral.sh/ruff/"]}
