agents:
  scout:
    role: scout
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: [repo_scan]
  architect:
    role: architect
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: []
  planner_cloud:
    role: architect
    llm:
      provider: ollama
      model: phi3:mini
      mode: hybrid
      hybrid_threshold_tokens: 0
    cache: in_memory
    tools: []
  critic:
    role: critic
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: []
  executor:
    role: executor
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: [scriptify]
  dynamics_scout:
    role: dynamics_scout
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: [repo_scan]
  sd_modeler:
    role: sd_modeler
    llm:
      provider: ollama
      model: phi3:mini
      mode: hybrid
      hybrid_threshold_tokens: 0
    cache: in_memory
    tools: []
  strategist:
    role: strategist
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: []
  ops_scout:
    role: ops_scout
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: [repo_scan]
  ops_researcher:
    role: ops_researcher
    llm:
      provider: ollama
      model: phi3:mini
      mode: hybrid
      hybrid_threshold_tokens: 0
    cache: in_memory
    tools: []
  ops_specialist:
    role: ops_specialist
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: []
  research_scout:
    role: research_scout
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: [repo_scan]
  insight_researcher:
    role: insight_researcher
    llm:
      provider: ollama
      model: phi3:mini
      mode: hybrid
      hybrid_threshold_tokens: 0
    cache: in_memory
    tools: []
  innovation_specialist:
    role: innovation_specialist
    llm:
      provider: ollama
      model: phi3:mini
      mode: local
    cache: in_memory
    tools: []
  judge:
    role: judge
    llm:
      provider: ollama
      model: phi3:mini
      mode: hybrid
      hybrid_threshold_tokens: 400
    cache: in_memory
    tools: []

crew:
  quick_fix:
    sequence:
      - scout
      - architect
      - critic
      - executor
  foresight_sd:
    sequence:
      - dynamics_scout
      - sd_modeler
      - strategist
      - critic
  ops_monitor:
    sequence:
      - ops_scout
      - ops_researcher
      - ops_specialist
      - judge
  research_monitor:
    sequence:
      - research_scout
      - insight_researcher
      - innovation_specialist
      - judge
