name: symbiont-autopilot

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps and run symbiont autopilot
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          python -m symbiont.cli init
          python -m symbiont.cli propose-here || true
          latest=$(python -m symbiont.cli latest-artifact --type script | grep apply_ || true)
          if [ -n "$latest" ]; then python -m symbiont.cli run-script "$latest" --yes || true; fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "symbiont: autopilot cycle"
          branch: symbiont/autopilot
          title: "Symbiont Autopilot: tiny refactors"
          body: |
            Generated by local-first symbiont. Includes artifacts/logs in data/.
            Review the plan and apply/rollback scripts before merging.

